#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
statusline_iseparator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
project_rooter_outermost = false
filemanager = "nerdtree"
bootstrap_before = "myspacevim#before"
# bootstrap_after = 'myspacevim#before'
autocomplete_method = 'coc'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
#    autocomplete_method = "ycm"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# 启用 format 模块
[[layers]]
name = 'format'
format_on_save = true

[[layers]]
name = "unite"
# sudo apt-get install silversearcher-ag

[options]
default_indent = 4

[[layers]]
name = "checkers"
show_cursor_error = false

[[layers]]
name = "lang#python"
python_interpreter = '/data/data/com.termux/files/usr/bin/python'
format_on_save = 1
format_on_save = true
enable_typeinfo = true
# pip install --user flake8 yapf autoflake isort

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#lua"

[[layers]]
name = "denite"

[[layers]]
name = 'git'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[layers]]
name = "ui"
enable_scrollbar = true

[[layers]]
name = 'tmux'

[[layers]]
name = "lsp"
filetypes = [
    "java",
    "python"
]

[[layers]]
name = "colorscheme"

[[layers]]
name = "core#t

[[layers]]
name = "git"
enable = true

[[layers]]
name = "lang#markdown"
enable = true